- name: Download and Extract
  ansible.builtin.copy:
    src: redis.repo
    dest: /etc/yum.repos.d/redis.repo

- name: Install REDIS
  ansible.builtin.package:
    name: redis-6.2.8
    state: present