- name: Install NodeJS
  ansible.builtin.package:
    name: "{{item}}"
    state: present
  loop:
    - python36
    - gcc
    - python3-devel

- name: Calling Nodejs function
  include_role:
    name: common
    tasks_from: create-user

- name: Calling download function
  include_role:
    name: common
    tasks_from: download

- name: display user id and group id
  ansible.builtin.debug:
    msg: "{{APPUSER_INFO}}"  ## we register this as a variable in create user common module

- name: Replace old uid
  ansible.builtin.replace:
    path: /home/roboshop/payment/payment.ini
    regexp: 'uid = 1'
    replace: 'uid = "{{APPUSER_INFO.uid}}"'
  remote_src: yes

- name: Replace old gid
  ansible.builtin.replace:
    path: /home/roboshop/payment/payment.ini
    regexp: 'gid = 1'
    replace: 'gid = "{{APPUSER_INFO.group}}"'
  remote_src: yes

- name: test
  ansible.builtin.shell: cat /home/roboshop/payment/payment.ini
  register: output

- name: Replace old gid
  ansible.builtin.debug:
    msg: "{{output}}" 

- name: Installing python dependencies 
  ansible.builtin.pip:
    requirements: /home/{{APPUSER}}/{{component}}/requirements.txt
    executable: pip3

