- name: Download and Extract
  ansible.builtin.copy:
    src: "{{component}}".repo
    dest: /etc/yum.repos.d/{{component}}.repo

- name: Install Mysql
  ansible.builtin.package:
    name: mysql-community-server
    state: present

- name: Enable and start {{component}}
  ansible.builtin.service:
    state: started
    name: mysqld
    enabled: yes

